# Generated by Django 4.1.1 on 2022-09-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
