# Generated by Django 4.1.1 on 2022-09-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_record_typer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                ("quotee", models.CharField(max_length=150)),
                ("text", models.TextField()),
                ("tags", models.TextField()),
            ],
        ),
    ]
